### ISSUE TITLE
Grid of dimension 1x1 is not displayed in OpenGL

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1688]
This is a very small issue, I know, but well :)

model : 

```
model new

global {}

grid cells width:1 height:1 {
	rgb color <- #red;
}

experiment my_experiment type:gui {
	output {
		display "openGL" type:opengl {
			grid cells;
		}
		display "java2D" {
			grid cells;
		}
	}
}
```

**Comment by AlexisDrogoul** [comment]
I close this issue as it is clearly not the case. OpenGL displays display 1x1 grids without problem.

![image](https://cloud.githubusercontent.com/assets/579256/14651359/d962e664-0699-11e6-8a82-211d313fa23f.png)

**Comment by mazarsju** [comment]
Well, it is the case for me. A Windows related problem maybe ?

<img width="961" alt="image1" src="https://cloud.githubusercontent.com/assets/12977635/14660731/fc3d5416-06d1-11e6-92eb-3a84e18d37da.png">

**Comment by hqnghi88** [comment]
HI Julien,
It works on my win.

**Comment by mazarsju** [comment]
That is so weird... Maybe a problem of graphical card then...

**Comment by AlexisDrogoul** [comment]
Or some preferences ? Do you have any preference for Displays/Performance turned on that could explain this behavior ?

**Comment by mazarsju** [comment]
No, all my preferences are the one by default...

**Comment by mazarsju** [comment]
Ok, when I run the simulation (synchronized), my cell appears red. But once I stop the simulation, it's white again.

**Comment by AlexisDrogoul** [comment]
I dont see any other solution than debugging step by step, then, to understand where your grid disappears...

**Comment by hqnghi88** [comment]
Hi,
More details, on my win, it is inverse with Julien's, it appear in initialisation, but when i run exp. , it start disappear and twinkling. But if we both turn "synchronize" of display on, it will be stabilized

**Comment by AlexisDrogoul** [comment]
In this model, we only display a 1x1 image stretched over the screen, and I guess the problem (and the solution) lie in the speed at which the display is refreshed by the simulation and a possible problem in the synchronization of the threads that handle the creation of textures and the one that handles the creation of scenes (and then the destruction of previous textures). What happens if you display a lot more agents on this grid ?

**Comment by hqnghi88** [comment]
You are right for the refreshed speed and synchronization problem. If i create 100 000 agents (dont need to display in "display"), it stabilized.
But, for the case of Julien, he always get a blank cell in initialisation. I dont have that issue.
Sorry if i am not clear enough.

**Comment by mazarsju** [comment]
If I create a lot of other agents (100000) in this unique cell, the problem remains the same. And when I play the simulation with the display synchronized, it twinkles between white and red (if I have no other agents, it remains red as long as the simulation runs).

**Comment by AlexisDrogoul** [comment]
Since I have fixed an issue during the Coding Camp, related to flashing/disappearing displays with very few agents, could you please test again this issue on Windows ? I can't reproduce on MacOS X, and I'm quite confident it may have been fixed...

**Comment by hqnghi88** [comment]
Dear Alexis,
It fixed for me. Let Julien confirm and close then.

**Comment by tcquang** [comment]
It works well for me also!

2016-06-04 17:50 GMT+07:00 hqnghi88 <notifications@github.com>:

> Dear Alexis,
> It fixed for me. Let Julien confirm and close then.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1688#issuecomment-223749371>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALRxbJC95OYfvp2IZA1pSdgxdrboJJSnks5qIViHgaJpZM4IKm5I>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153

**Comment by AlexisDrogoul** [comment]
OK. I close it -- unless @mazarsju sees the phenomenon again, in which case, reopen it !

**Comment by mazarsju** [comment]
Well, the problem is still here for me... Exactly the same behavior. If I disable my graphic card, it works fine (I don't remember if it was the case before). I think it is really a problem linked to my graphical card, and the problem is not very important, so I let the issue close
