### ISSUE TITLE
current_edge does not match current_path[0]

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2506]
**Describe the bug**
With moving skills, you get some in-built attributes for the agent such as `current_edge` and `current_path` among many others like heading and real_speed etc. I have observed that current_edge does not **always** match the first element of the list in `current_path`

**To Reproduce**
In any moving skills model, such as the traffic model, you can open the agent attribute table and look at `current_edge` and `current_path`. Here you will see discrepancy in these two attributes. It is not straightaway visible but if you click the model step-by-step, on many occasions you will see this occur. I doubt this is happening when agent is changing edges to reach the next edge on the graph. It happens for sure, and I have checked it many times that they both do not match.

**Expected behavior**
Consistency in the two attributes or a some note in the documentation to highlight this if it cannot be resolved or a note to clarify why and when they are different how to workaround this?

**Screenshots**
I will add soon.

**Desktop (please complete the following information):**

**Additional context**

**Comment by AlexisDrogoul** [comment]
I have assigned Patrick to this. I wouldn't label it as bug, by the way, as it would mean that the `current_edge` always represents the first segment of the `current_path`. But is this always true ?

**Comment by sriramab** [comment]
I come back to this one. If you run this model, the current_edge is never detected (in reflex keep_moving), while the inspect box clearly shows that the agent car has a current_edge. Unless I am doing a mistake, I dont understand this, can someone please try this model

```php

/***
* Name: maintenance
* Author: bhami001
* Description: 
* Tags: Tag1, Tag2, TagN
***/

model maintenance

global {
	/** Insert the global definitions, variables and actions here */
	
	list<geometry> road_input <- [polyline({10,10}, {60,10}), polyline({60,10},{60,60}),polyline({60,60},{10,60}),polyline({10,60},{10,10}), polyline({10,10},{60,60})];
	file shape_file_roads <- file('../includes/NLtraced.shp');
	//geometry shape <- envelope(road_input);
	float step <- 0.5#h;
	graph g;
	//int edge_cars ;
	init{
		create roads from:road_input;
		g<- as_edge_graph(roads);
		create districts number:length(g.vertices){
			shape <- square(4);
		}
		
		
		
		loop i from:0 to: length(g.vertices)-1{
			districts[i].location <- g.vertices[i];
		}
		
		create cars number:550{
			 home <- one_of(districts);
	 		office <- one_of(districts -home);
	 		location <- home.location;
		}
	}
	
}

species roads{
	int age <- rnd(20);
	string health <- one_of(["1","2","3","4","5"]);
	int edge_cars;
	aspect default {
		draw shape  color:#gray ;
	}
	
	reflex speed_modify{
		edge_cars <- length(cars at_distance 1);
	}
	
}

species cars skills:[moving]{
	districts home ;
	districts office ;
	districts next_target;
	int speed_factor;
	
	init{
		//next_target <- office;
	}
	
	
	reflex keep_moving {
		speed_factor <- max([0,(self.current_edge as roads).edge_cars]);
		write speed_factor;
		do goto target:office on:g speed:(100.0-speed_factor*5) #km/#h;
	}
	
	
	aspect default{
		draw circle(1) color:#blue;
	}
}


species districts{
	aspect default {
		draw shape  color:#gray ;
	}
}



experiment maintenance type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
		display d{
			
			species districts;
			species roads;
			species cars;
		}
	}
}

```

**Comment by AlexisDrogoul** [comment]
@sriramab 
Difficult to run anything without the data..

**Comment by sriramab** [comment]
@AlexisDrogoul  No data needed, It is a standalone example.... it just appears like it needs shapefiles, but it does not need any external files

**Comment by sriramab** [comment]
I must admit, that since I made the example for a country scale (1000's of km of roads), then I switched to a simple reproducible example  and i forgot to change the speed accordingly, ...... so may be you have to correct the speeds and time step a little bit. sorry for that

**Comment by AlexisDrogoul** [comment]
So `file shape_file_roads <- file('../includes/NLtraced.shp');` is just here for decoration ? 😄

**Comment by sriramab** [comment]
:) i corrected the example, may be you can copy again.

**Comment by AlexisDrogoul** [comment]
In your model, it is obvious that current_edge will be null sometimes since you reference it before you call goto. Is it the problem you're facing ?

**Comment by sriramab** [comment]
Hi

It know it is stupid, but I tried current_edge both before and after the goto call, but I get the same error. I put an initial value for speed_factor as 0, but from second cycle speed_factor should come from the simulation. And in both cases I get this warning that target is nil ? do you not get this? and why do you say "sometimes"?

```php
1 occurence in cars1 at cycle 0: Cannot evaluate edge_cars as the target agent is nil
in speed_factor <- roads(current_edge).edge_cars;
in speed_factor <- roads(current_edge).edge_cars;
in agent cars1
```

**Comment by AlexisDrogoul** [comment]
Well. This simply means that current_edge is nil sometimes. There are probably a number of reasons for this (the agent has still not yet moved, etc.). Maybe you can try, with only one agent (and not 50), to write the values of current_edge first after each execution of the reflex. If it always nil, there is probably a problem somewhere.

**Comment by ptaillandier** [comment]
Alexis is right. current_edge is nil by default (at the creation of the agent) and is recomputed each time the goto action is called (to be more precise, at the end of the action). I tested the model with one agent, and we can see clearly that at the first step current_edge is nil, and then, after current_edge has the right value.

**Comment by sriramab** [comment]
Thank you Patrick. This is already some days ago and as I remember, even when the agent is in motion, the current_edge does not match the current_path[0], could you please check for me, then we can may be close this issue.

**Comment by sriramab** [comment]
Hmm, I think it could be your explanation "if it moves slowly", but I am sure there was something not right. I understand what you are saying.  For now I make close this and sorry for labeling as bug.
