### ISSUE TITLE
Exception: Can't load library: /System/Library/Frameworks/gluegen-rt.Framework/gluegen-rt

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#869]
This exception, raised when an OpenGL view is opened, was only shown on @ptaillandier machine, but is now showing on mine too. For an unknown reason, JOGL is fooled and looks for gluegen-rt in the system Frameworks, while it is being told of going to look into its own libraries. 

One reason could reside in the OpenGL pipeline of Java2D, since the error seems to manifest itself when both Java2D and OpenGL displays are created or when Java2D displays are displayed before OpenGL ones.

**Comment by AlexisDrogoul** [comment]
I have posted a request in the Jogamp forum: http://forum.jogamp.org/Return-of-the-quot-java-lang-UnsatisfiedLinkError-Can-t-load-library-System-Library-Frameworks-glueg-td4034549.html

Hope we will have answers ! (by the way, I suspect the problem to lie on the default JDK now used by Luna, which requires — compared to JDK 6 — a different format of shared libraries; we will see).

**Comment by AlexisDrogoul** [comment]
I have pushed a first attempt at fixing this issue. Please test and tell me whether it works or not (https://github.com/gama-platform/gama/commit/a5093246741396262aebc41b5f38c45a94431fbf)

**Comment by ptaillandier** [comment]
It is not working (still the same error)

**Comment by AlexisDrogoul** [comment]
Can you try: (1) to restart your Mac; (2) make sure you run GAMA using the 1.7 or 1.8 JDK (not 1.6). It is now (re)working on mine, so I dont really get what is happening…

Try also to look in these places for traces of j3D or gluegen or jogl … (if you find any, remove them).

/Users/YOUR_NAME/Library/Java/Extensions
/Library/Java/JavaVirtualMachines/YOUR_JDK/Contents/Home/jre/lib/ext
/Library/Java/Extensions
/Network/Library/Java/Extensions
/System/Library/Java/Extensions
/usr/lib/java

**Comment by ptaillandier** [comment]
I removed all traces of  j3D or gluegen or jogl, installed java 1.8, restarted my computer, set the ran GAMA with java 1.8.... but I still have the same error....

**Comment by AlexisDrogoul** [comment]
Hum… Well. Can you (a bit in blind mode) replace the static portion of SWTLayeredDisplayView with this one: 

	static {
		// Necessary to load the native libraries correctly
		JarUtil.setResolver(new JarUtil.Resolver() {

			@Override
			public URL resolve(final URL url) {
				try {
					System.out.println("Original URL: " + url + " ");
					final URL result = FileLocator.resolve(url);
					System.out.println("Resulting URL: " + result);
					return result;
				} catch (IOException ioexception) {
					return url;
				}
			}
		});
	}

and send me (or publish here) the result ?

**Comment by ptaillandier** [comment]
Here the obtained results:

Original URL:
bundleresource://225.fwk858232531:5/com/jogamp/common/os/Platform.class

Resulting URL: jar:file:/Applications/eclipse
Luna/../../Users/administrateur/git/gama/ummisco.gama.opengl/gluegen-rt.jar!/com/jogamp/common/os/Platform.class


!ENTRY org.eclipse.e4.ui.workbench 4 0 2015-06-01 13:10:11.287

!MESSAGE Unable to create class
'org.eclipse.ui.internal.e4.compatibility.CompatibilityView' from bundle
'162'

!STACK 0

org.eclipse.e4.core.di.InjectionException: java.lang.UnsatisfiedLinkError:
Can't load library:
/System/Library/Frameworks/gluegen-rt.Framework/gluegen-rt

at org.eclipse.e4.core.internal.di.MethodRequestor.execute(
MethodRequestor.java:62)

at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(
InjectorImpl.java:888)

at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(
InjectorImpl.java:869)

at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120
)

at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(
InjectorImpl.java:337)

at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:258)

at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(
ContextInjectionFactory.java:162)

..... other lines.....

        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(
PartServiceImpl.java:1149)

at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1318)

at org.eclipse.ui.internal.WorkbenchPage.busyShowView(
WorkbenchPage.java:1283)

at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4208)

at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)

at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4204)

at msi.gama.gui.swt.SwtGui$13.run(SwtGui.java:446)

at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)

at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:156)

at org.eclipse.swt.widgets.Display.syncExec(Display.java:4732)

at msi.gama.gui.swt.SwtGui.run(SwtGui.java:942)

at msi.gama.gui.swt.SwtGui.internalShowView(SwtGui.java:438)

at msi.gama.gui.swt.SwtGui.showView(SwtGui.java:552)

at msi.gama.common.util.GuiUtils.showView(GuiUtils.java:154)

at msi.gama.outputs.AbstractDisplayOutput$1.run(
AbstractDisplayOutput.java:40)


2015-06-01 11:11 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
All right. Can you try 3 things:

1) Verify that you have write access to Users/administrateur/git/gama/ummisco.gama.opengl (you probably have, but it's worth checking, because maybe you're not logged in as "administrateur")
2) If you change the path to eclipse from "eclipse Luna" to "eclipseLuna" (no space, no other character), does it change anything ? 
3) In the Eclipse workspace, refresh the ummisco.gama.opengl project

…

**Comment by ptaillandier** [comment]
Hi,

1) Verify that you have write access to
Users/administrateur/git/gama/ummisco.gama.opengl
(you probably have, but it's worth checking, because maybe you're not
logged in as "administrateur")
I was already administrator of my computer
2) If you change the path to eclipse from "eclipse Luna" to "eclipseLuna"
(no space, no other character), does it change anything ?
I changed this

3) In the Eclipse workspace, refresh the ummisco.gama.opengl project
It did this

By miracle (maybe thanks to point 2 or 3?), it seems to work now !

Cheers and thanks,

Patrick

2015-06-02 9:10 GMT+02:00 Alexis Drogoul <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Hi,

Point 2 is the likely cause. And it is not a miracle, as far as I know :)  It seems that FileLocator.resolve(…) returns a non-encoded URL, while the JOGL JarUtil class expects an encoded one (with spaces turned into %20 characters or something like this). I however awaits a confirmation from the JogAmp team to go on with a bug fix that would encode the URL on the fly (see http://forum.jogamp.org/Return-of-the-quot-java-lang-UnsatisfiedLinkError-Can-t-load-library-System-Library-Frameworks-glueg-td4034549.html#a4034569). 

I'm also not sure it is the only cause, as the error appeared on my computer, where I ***don't*** use space characters. 

Cheers
Alexis
